@startuml C4_Context_Diagram
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

LAYOUT_WITH_LEGEND()

Person(ngo, "Cleanup NGO", "Do targeted cleanups.")
Person(user, "General Public", "Get information on marine debris.")
System(OceanEcoWatch, "Ocean EcoWatch", "Monitors marine debris with satellite data.")
System_Ext(SentinelHub, "Sentinel Hub", "Provides satellite data.")

Rel(ngo, OceanEcoWatch, "Uses")
Rel(user, OceanEcoWatch, "Uses")
Rel(OceanEcoWatch, SentinelHub, "Gets satellite images from", "https <<==>>")

@enduml
