@startuml system_context_diagram
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

LAYOUT_WITH_LEGEND()

Person(ngo, "Cleanup NGO", "Do targeted cleanups.")
Person(user, "General Public", "Get information on marine debris.")
System(OceanEcoWatch, "Ocean Eco Watch", "Monitors marine debris with satellite data.")
System_Ext(SentinelHub, "Sentinel Hub", "Provides satellite data.")
System_Ext(AwsRds, "AWS RDS", "PostGIS database for storing vector data.")
System_Ext(AwsS3, "AWS S3", "Stores satellite images and prediction raster data.")
System_Ext(AwsElasticBeanstalk, "AWS Elastic Beanstalk", "Hosts backend API.")
System_Ext(AwsElasticLoadBalancing, "AWS Elastic Load Balancing", "Distributes incoming traffic.")
System_Ext(Strato, "Strato", "Hosts frontend web app.")
System_Ext(Runpod, "Runpod", "Serverless GPU for running prediction models.")
System_Ext(GithubActions, "Github Actions", "Runs prediction service")

Rel(ngo, OceanEcoWatch, "Uses")
Rel(user, OceanEcoWatch, "Uses")
Rel(OceanEcoWatch, SentinelHub, "Gets satellite images from")
Rel(OceanEcoWatch, AwsRds, "Stores data in")
Rel(OceanEcoWatch, AwsS3, "Stores data in")
Rel(OceanEcoWatch, AwsElasticBeanstalk, "Hosted on")
Rel(OceanEcoWatch, AwsElasticLoadBalancing, "Uses")
Rel(OceanEcoWatch, Strato, "Hosted on")
Rel(OceanEcoWatch, Runpod, "Runs prediction models on")
Rel(OceanEcoWatch, GithubActions, "Runs prediction service on")


@enduml
