name: Format and Lint

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Format and Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install black isort ruff
      - name: Format with black
        run: black .

      - name: Format with isort
        run: isort . --profile black
      - name: Lint with ruff
        run: ruff --output-format=github .
