name: Scheduled Plastic Detection

# on:
#   schedule:
#     # Runs every minute for testing purposes
#     - cron: "* * * * *"
on:
  pull_request:
    branches:
      - main

jobs:
  plastic-detection-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gdal-bin libgdal-dev
          echo gdal-config --version
      - name: Install Python dependencies and GDAL
        run: |
          pip install -r requirements.txt
          pip install GDAL==$(gdal-config --version)
      - name: Run plastic detection script
        run: python main.py
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PW: ${{ secrets.DB_PW }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          SH_CLIENT_ID: ${{ secrets.SH_CLIENT_ID }}
          SH_CLIENT_SECRET: ${{ secrets.SH_CLIENT_SECRET }}
          SH_INSTANCE_ID: ${{ secrets.SH_INSTANCE_ID }}
