name: Scheduled Plastic Detection

on:
  pull_request:
    branches:
      - main

jobs:
  plastic-detection-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install build tools and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential software-properties-common
          sudo apt-get install -y libproj-dev proj-data proj-bin
          sudo apt-get install -y libgeos-dev
          sudo apt-get install -y libjson-c-dev
          # Add other necessary dependencies here

      - name: Install CMake and other build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++  # Install CMake and g++

      - name: Download, compile, and install GDAL
        run: |
          wget http://download.osgeo.org/gdal/3.7.2/gdal-3.7.2.tar.gz
          tar xvfz gdal-3.7.2.tar.gz
          cd gdal-3.7.2

          # Use CMake to configure, build, and install GDAL
          mkdir build
          cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local
          cmake --build . -- -j$(nproc)
          sudo cmake --install .

      - name: Update library path
        run: |
          echo "/usr/local/lib" | sudo tee -a /etc/ld.so.conf.d/gdal.conf
          sudo ldconfig

      - name: Set GDAL environment variables
        run: |
          echo "CPLUS_INCLUDE_PATH=/usr/local/include/gdal" >> $GITHUB_ENV
          echo "C_INCLUDE_PATH=/usr/local/include/gdal" >> $GITHUB_ENV

      - name: Install Python GDAL bindings
        run: |
          GDAL_VERSION=$(ogrinfo --version | grep -oP '(?<=GDAL )\d+(\.\d+)+')
          pip install GDAL==$GDAL_VERSION

      - name: Install other Python dependencies
        run: pip install -r requirements.txt

      - name: Run plastic detection script
        run: python main.py
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PW: ${{ secrets.DB_PW}}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          SH_CLIENT_ID: ${{ secrets.SH_CLIENT_ID }}
          SH_CLIENT_SECRET: ${{ secrets.SH_CLIENT_SECRET }}
          SH_INSTANCE_ID: ${{ secrets.SH_INSTANCE_ID }}
          SAGEMAKER_ROLE: ${{ secrets.SAGEMAKER_ROLE }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
