name: Scheduled Plastic Detection

# on:
#   schedule:
#     # Runs every minute for testing purposes
#     - cron: "* * * * *"
on:
  pull_request:
    branches:
      - main
jobs:
  plastic-detection-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: "main"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install build tools and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential software-properties-common
          sudo apt-get install -y libproj-dev proj-data proj-bin
          sudo apt-get install -y libgeos-dev
          sudo apt-get install -y libgdal-dev
          sudo apt-get install -y libjson-c-dev
      - name: Download GDAL source
        run: |
          GDAL_VERSION="3.7.2"
          wget http://download.osgeo.org/gdal/$GDAL_VERSION/gdal-$GDAL_VERSION.tar.gz
          tar -xzf gdal-$GDAL_VERSION.tar.gz
      - name: Compile GDAL
        run: |
          cd gdal-$GDAL_VERSION
          ./configure --prefix=/usr/local
          make -j$(nproc)  # Compiles using all available cores
      - name: Install GDAL
        run: |
          sudo make install
          sudo ldconfig  # Update shared library cache.
      - name: Verify GDAL installation
        run: |
          gdalinfo --version
      - name: Run plastic detection script
        run: python main.py
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PW: ${{ secrets.DB_PW}}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          SH_CLIENT_ID: ${{ secrets.SH_CLIENT_ID }}
          SH_CLIENT_SECRET: ${{ secrets.SH_CLIENT_SECRET }}
          SH_INSTANCE_ID: ${{ secrets.SH_INSTANCE_ID }}
